# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailcx < Formula
  desc "CLI for Mail.cx — Email Testing Platform & API for Developers"
  homepage "https://mail.cx"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.1.0/mailcx_1.1.0_darwin_amd64.tar.gz"
      sha256 "9ba22d2ee58a14d3c53c10dfd39330ab2e0abb3a9aa232ecefcadeb637770cb7"

      define_method(:install) do
        bin.install "mailcx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.1.0/mailcx_1.1.0_darwin_arm64.tar.gz"
      sha256 "0a3d959aada8a0838b42d1761aacfeabae38524afd4571467382905e1e999740"

      define_method(:install) do
        bin.install "mailcx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.1.0/mailcx_1.1.0_linux_amd64.tar.gz"
      sha256 "8688aac52ce27b340338c959fb40624af62d3ec160bd0066c650b8b0448411af"
      define_method(:install) do
        bin.install "mailcx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.1.0/mailcx_1.1.0_linux_arm64.tar.gz"
      sha256 "41a5cca466b1dd66336285312f0dcf34406f2d954bbd36293c3678f90f8d7b4d"
      define_method(:install) do
        bin.install "mailcx"
      end
    end
  end

  test do
    system "#{bin}/mailcx", "--version"
  end
end
