# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailcx < Formula
  desc "CLI for Mail.cx — Email Testing Platform & API for Developers"
  homepage "https://mail.cx"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.1/mailcx_1.2.1_darwin_amd64.tar.gz"
      sha256 "18ffb8a6c59fb52167c2fbd304e218c6741fedd6fde74c82ffb5228b6e50f09d"

      define_method(:install) do
        bin.install "mailcx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.1/mailcx_1.2.1_darwin_arm64.tar.gz"
      sha256 "3c4456e90f7deaa8a959ddab45097c334110938eb3414048f3d29b21cfe03896"

      define_method(:install) do
        bin.install "mailcx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.1/mailcx_1.2.1_linux_amd64.tar.gz"
      sha256 "47b670d10fe943769e90ee06cc28cff9239d353200dcc2e6ffcfe89c33128348"
      define_method(:install) do
        bin.install "mailcx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.1/mailcx_1.2.1_linux_arm64.tar.gz"
      sha256 "36c82d66d9ddc8aa7db4e401919b6ba52a4842057818b92996d912ee2b0c6a22"
      define_method(:install) do
        bin.install "mailcx"
      end
    end
  end

  test do
    system "#{bin}/mailcx", "--version"
  end
end
