# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtd < Formula
  desc "CLI for Mail.td — Developer Email Testing Platform & API"
  homepage "https://mail.td"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.3.0/mailtd_1.3.0_darwin_amd64.tar.gz"
      sha256 "4073a902940d0f0a384fcaf73869e6e3a4379b48be9a26983989a30e562926dd"

      define_method(:install) do
        bin.install "mailtd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.3.0/mailtd_1.3.0_darwin_arm64.tar.gz"
      sha256 "5e7a7eda58288d6462f66c1a86d4d53eab7ea5295be98c0a178c0495549c2e24"

      define_method(:install) do
        bin.install "mailtd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.3.0/mailtd_1.3.0_linux_amd64.tar.gz"
      sha256 "62fe3c2f3caa9f1391fadfe3270dccd8ee531518a1bdcff9b27c9d25d941394e"
      define_method(:install) do
        bin.install "mailtd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.3.0/mailtd_1.3.0_linux_arm64.tar.gz"
      sha256 "da752ff3d1c766a1eb2e6f227f9b82a1ecb339023843081ea07cb7a085ee39f4"
      define_method(:install) do
        bin.install "mailtd"
      end
    end
  end

  test do
    system "#{bin}/mailtd", "--version"
  end
end
