# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtd < Formula
  desc "CLI for Mail.td — Developer Email Testing Platform & API"
  homepage "https://mail.td"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.0.0/mailtd_1.0.0_darwin_amd64.tar.gz"
      sha256 "837fbac22703341e3731168254e6c691b251049181cd6d7b23d73c341fb9bb00"

      define_method(:install) do
        bin.install "mailtd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.0.0/mailtd_1.0.0_darwin_arm64.tar.gz"
      sha256 "7f72e324a85dacf92d29a51fce62e00528d4a0630a68a1ba87916f1f566640bf"

      define_method(:install) do
        bin.install "mailtd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.0.0/mailtd_1.0.0_linux_amd64.tar.gz"
      sha256 "25b6b3de4a0564896ba32ea6d341fd5be11b1edd7617b0688309565fdd5b39bb"
      define_method(:install) do
        bin.install "mailtd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.0.0/mailtd_1.0.0_linux_arm64.tar.gz"
      sha256 "4b27b599735300ce7b1b76be009de4c860f0196ac22b5e36e2eec978c4b2ebdd"
      define_method(:install) do
        bin.install "mailtd"
      end
    end
  end

  test do
    system "#{bin}/mailtd", "--version"
  end
end
