# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailcx < Formula
  desc "CLI for Mail.cx — Email Testing Platform & API for Developers"
  homepage "https://mail.cx"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.0/mailcx_1.2.0_darwin_amd64.tar.gz"
      sha256 "4170bff2e1c42a0b1e3fa3f2bcc0bdade851cc5a8dfa996a6b4e06059a4fdeaf"

      define_method(:install) do
        bin.install "mailcx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.0/mailcx_1.2.0_darwin_arm64.tar.gz"
      sha256 "ae528c3c60f633e0d2fb134db7d8f16cac6f4ab7515d4776d26b476d8938b9f8"

      define_method(:install) do
        bin.install "mailcx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.0/mailcx_1.2.0_linux_amd64.tar.gz"
      sha256 "1f3fccd83d7601a9a428ee172d99e16d0056466cf886d99bf6a8664a3f81e77b"
      define_method(:install) do
        bin.install "mailcx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailcx-cli/releases/download/v1.2.0/mailcx_1.2.0_linux_arm64.tar.gz"
      sha256 "a61cf2c7487bf09e846d241b3f8bc832feb35caa725cf606e37fca645f103b2e"
      define_method(:install) do
        bin.install "mailcx"
      end
    end
  end

  test do
    system "#{bin}/mailcx", "--version"
  end
end
