# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailtd < Formula
  desc "CLI for Mail.td — Developer Email Testing Platform & API"
  homepage "https://mail.td"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.2.0/mailtd_1.2.0_darwin_amd64.tar.gz"
      sha256 "09d10415b581231cf0721bea359babe7712b14479066be53c074916bb9e310e1"

      define_method(:install) do
        bin.install "mailtd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.2.0/mailtd_1.2.0_darwin_arm64.tar.gz"
      sha256 "eb9fe85bbb69c41d0bce2cae8b325ae2e1f2529f75c0eff62e1d086b179c79e4"

      define_method(:install) do
        bin.install "mailtd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.2.0/mailtd_1.2.0_linux_amd64.tar.gz"
      sha256 "784df1a020027f124b0eeef90d1576986a4c9658db6127e3c3afc6cf5abc8bbb"
      define_method(:install) do
        bin.install "mailtd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mailtd/mailtd-cli/releases/download/v1.2.0/mailtd_1.2.0_linux_arm64.tar.gz"
      sha256 "00f63129c5373c2d10b56af1f898eaa7c334893b75771135e64b82f0c2196dfc"
      define_method(:install) do
        bin.install "mailtd"
      end
    end
  end

  test do
    system "#{bin}/mailtd", "--version"
  end
end
